# https://docs.docker.com/compose/compose-file/
version: "3.6"

# https://docs.docker.com/compose/compose-file/#networks
networks:
  nginx:

services:
  nginx:
    container_name: nginx
    image: nginx:1.17
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certificates:/etc/nginx/certificates
    ports:
      - "443:443"
    networks:
      - "nginx"